src/CarroiridianBundle/Entity/Compra.php
<?php

namespace CarroiridianBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use PagosPayuBundle\Entity\RepuestaPago;

/**
 * Compra
 *
 * @ORM\Table(name="compra")
 * @ORM\Entity(repositoryClass="CarroiridianBundle\Repository\CompraRepository")
 */
class Compra
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var guid
     *
     * @ORM\Column(name="guid", type="guid")
     */
    private $guid;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $createdAt;

    /**
     * The user who made the purchase.
     *
     * @var User
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User", inversedBy="compras")
     */
    protected $comprador;

    /**
     * Items that have been purchased.
     *
     * @var Compraitem[]
     * @ORM\OneToMany(targetEntity="CarroiridianBundle\Entity\Compraitem", mappedBy="compra", cascade={"remove"})
     */
    protected $compraitems;

    /**
     * Items that have been purchased.
     *
     * @var Bonos[]
     * @ORM\OneToMany(targetEntity="CarroiridianBundle\Entity\Bono", mappedBy="valorbono", cascade={"remove"})
     */
    protected $bonos;

    /**
     * Items that have been purchased.
     *
     * @var Comprabono[]
     * @ORM\OneToMany(targetEntity="CarroiridianBundle\Entity\Bono", mappedBy="compra", cascade={"remove"})
     */
    protected $comprabonos;

    /**
     * @var float
     *
     * @ORM\Column(name="precio", type="float", nullable=true)
     */
    private $precio;

    /**
     * @ORM\ManyToOne(targetEntity="CarroiridianBundle\Entity\EstadoCarrito")
     * @ORM\JoinColumn(name="eatadocarrito_id", referencedColumnName="id")
     */
    protected $estado;

    /**
     * @var boolean
     *
     * @ORM\Column(name="prueba", type="boolean")
     */
    private $prueba;

    /**
     * @var string
     *
     * @ORM\Column(name="descripcion", type="text", nullable=true)
     */
    private $descripcion;

    /**
     * @ORM\ManyToOne(targetEntity="CarroiridianBundle\Entity\Envio")
     * @ORM\JoinColumn(name="direccion_id", referencedColumnName="id", nullable=true, onDelete="SET NULL")
     */
    protected $direccion;

    /**
     * Items that have been purchased.
     *
     * @var RepuestaPago[]
     * @ORM\OneToMany(targetEntity="PagosPayuBundle\Entity\RepuestaPago", mappedBy="compra", cascade={"remove"})
     */
    protected $RespuestasPago;

    /**
     * @var boolean
     *
     * @ORM\Column(name="pago", type="boolean")
     */
    private $pago = false;

    /**
     * @var string
     *
     * @ORM\Column(name="tipo_pago", type="string", length=255)
     */
    private $tipo_pago;


    public function __toString()
    {
        return $this->getId().' ';
    }

    /**
     * (Initialize some fields).
     */
    public function __construct()
    {
        $this->id = $this->generateId();
        $this->guid = $this->id;
        $this->compraitems = new ArrayCollection();
        $this->createdAt = new \DateTime();

    }

    /**
     * @param int $storeId
     *
     * @return string
     */
    public function generateId($storeId = 1)
    {
        return preg_replace('/[^0-9]/i', '', sprintf('%d%d%03d%s', $storeId, date('Y'), date('z'), microtime()));
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set guid
     *
     * @param guid $guid
     *
     * @return Compra
     */
    public function setGuid($guid)
    {
        $this->guid = $guid;
    
        return $this;
    }

    /**
     * Get guid
     *
     * @return guid
     */
    public function getGuid()
    {
        return $this->guid;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     *
     * @return Compra
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    
        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set comprador
     *
     * @param \AppBundle\Entity\User $comprador
     *
     * @return Compra
     */
    public function setComprador(\AppBundle\Entity\User $comprador = null)
    {
        $this->comprador = $comprador;

        return $this;
    }

    /**
     * Get comprador
     *
     * @return \AppBundle\Entity\User
     */
    public function getComprador()
    {
        return $this->comprador;
    }

    /**
     * Add compraitem
     *
     * @param \CarroiridianBundle\Entity\Compraitem $compraitem
     *
     * @return Compra
     */
    public function addCompraitem(\CarroiridianBundle\Entity\Compraitem $compraitem)
    {
        $this->compraitems[] = $compraitem;
    
        return $this;
    }

    /**
     * Remove compraitem
     *
     * @param \CarroiridianBundle\Entity\Compraitem $compraitem
     */
    public function removeCompraitem(\CarroiridianBundle\Entity\Compraitem $compraitem)
    {
        $this->compraitems->removeElement($compraitem);
    }

    /**
     * Get compraitems
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getCompraitems()
    {
        return $this->compraitems;
    }

    /**
     * Set bonos
     *
     * @param \CarroiridianBundle\Entity\Bono $bono
     *
     * @return Compra
     */
    public function setBono(\CarroiridianBundle\Entity\Bono $bono = null)
    {
        $this->bono = $bono;

        return $this;
    }

    /**
     * Get bonos
     *
     * @return \CarroiridianBundle\Entity\Bono
     */
    public function getBonos()
    {
        return $this->bonos;
    }


    /**
     * Set prueba
     *
     * @param boolean $prueba
     *
     * @return Compra
     */
    public function setPrueba($prueba)
    {
        $this->prueba = $prueba;
    
        return $this;
    }

    /**
     * Get prueba
     *
     * @return boolean
     */
    public function getPrueba()
    {
        return $this->prueba;
    }

    /**
     * Set descripcion
     *
     * @param string $descripcion
     *
     * @return Compra
     */
    public function setDescripcion($descripcion)
    {
        $this->descripcion = $descripcion;
    
        return $this;
    }

    /**
     * Get descripcion
     *
     * @return string
     */
    public function getDescripcion()
    {
        return $this->descripcion;
    }

    /**
     * Set estado
     *
     * @param \CarroiridianBundle\Entity\EstadoCarrito $estado
     *
     * @return Compra
     */
    public function setEstado(\CarroiridianBundle\Entity\EstadoCarrito $estado = null)
    {
        $this->estado = $estado;
    
        return $this;
    }

    /**
     * Get estado
     *
     * @return \CarroiridianBundle\Entity\EstadoCarrito
     */
    public function getEstado()
    {
        return $this->estado;
    }

    /**
     * Set direccion
     *
     * @param \CarroiridianBundle\Entity\Envio $direccion
     *
     * @return Compra
     */
    public function setDireccion(\CarroiridianBundle\Entity\Envio $direccion = null)
    {
        $this->direccion = $direccion;
    
        return $this;
    }

    /**
     * Get direccion
     *
     * @return \CarroiridianBundle\Entity\Envio
     */
    public function getDireccion()
    {
        return $this->direccion;
    }

    /**
     * Set precio
     *
     * @param float $precio
     *
     * @return Compra
     */
    public function setPrecio($precio)
    {
        $this->precio = $precio;
    
        return $this;
    }

    /**
     * Get precio
     *
     * @return float
     */
    public function getPrecio()
    {
        return $this->precio;
    }

    /**
     * Get Usuario
     *
     * @return string
     */
    public function getUsuario()
    {
        $user = $this->getDireccion()->getUser();
	    if($user != null){
		    return $user->getNombre().' '.$user->getApellidos();
	    }else if($this->getComprador() != null){
		    return $this->getComprador()->getEmail();
	    }else{
		    return "NO IDENTIFICADO";
	    }
    }

    /**
     * Get Email
     *
     * @return string
     */
    public function getEmail()
    {
        $user = $this->getDireccion()->getUser();
	    if($user != null){
		    return $user->getEmail();
	    }else if($this->getComprador() != null){
		    return $this->getComprador()->getEmail();
	    }else{
	    	return "NO IDENTIFICADO";
	    }
    }

    /**
     * Get Telefono
     *
     * @return string
     */
    public function getTelefono()
    {
        $user = $this->getDireccion()->getUser();
        return $user->getTelefono();
    }

    /**
     * Get UsuarioCompleto
     *
     * @return string
     */
    public function getUsuarioCompleto()
    {
        if($this->getDireccion() != null){
            $user = $this->getDireccion()->getUser();
            //exit(dump($this->getDireccion()));
            if($user != null){
                $nombre = $user->getNombre().' '.$user->getApellidos();
                $cad = '<table class="table table-bordered">';
                $cad .= '<tr><td><strong>Nombre</strong></td><td>'.$nombre.'</td></tr>';
                $cad .= '<tr><td><strong>Email</strong></td><td>'.$user->getEmail().'</td></tr>';
                $cad .= '<tr><td><strong>Telefono</strong></td><td>'.$user->getTelefono().'</td></tr>';
                $cad .= '</table>';
                return $cad;
            }else{
	            $user = $this->getComprador();
	            if($user != null){
		            $nombre = $user->getNombre().' '.$user->getApellidos();
		            $cad = '<table class="table table-bordered">';
		            $cad .= '<tr><td><strong>Nombre</strong></td><td>'.$nombre.'</td></tr>';

src/CarroiridianBundle/Resources/views/Default/box.html.twig
{% extends 'lay_iridian.html.twig' %}
    {% set lc = app.request.locale %}

{% block content %}

       <div class="container-fluid">
            <div class="row">
                <div class="the_produc">
                    <div class="col-lg-1 col-md-1 col-sm-12 col-xs-12"></div>
                    <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">
                        <div class="txt">
                            <h2>{{ producto.nombre }}</h2>
                            {{ producto.gen("descripcion",lc) | raw }}
                                                   <hr>
                            <h3>${{ producto.precio | number_format }}</h3>

                        {% if app.user %}
                        {% else %}
                            <a class="button button2" href="{{ path('registro_login') }}?ruta={{ path('boxplan',{'id':producto.id,'nombre':producto.nombre}) }}">
                                <span> {{ qi.textoDB('box_send') }}</span>
                              </a>
                        {% endif %}
                        </div>

                        </div>
                   <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">
                       <div class="img">
                       <img alt="" src="{{ (path_productos ~'/'~ producto.imagen) | imagine_filter('prod_rot_gal') }}"/>
                       </div>


                    </div>

                    <div class="col-sm-12 col-lg-12">
                        {% if app.user %}
                            {% if estado %}
                                <h4>Tienes una suscripción {{ estado }}</h4>
                            {% else %}
                        <div class="the_produc">
                                <h4>{{ qi.textoDB('preferencias_box') }}</h4>
                                <div class="row direccion2">
                                    <div class="col-lg-12">
                                        {{ form_start(form) }}
                                        <div class="col-lg-6">
                                            <label>{{ qi.textoDB('text_genero_form_box') }}</label>
                                            {{ form_widget(form.genero) }}
                                        </div>
                                        <div class="col-lg-6">
                                            <label>{{ qi.textoDB('text_form_talla_c_box') }}</label>
                                            {{ form_widget(form.tallacamiseta) }}
                                        </div>
                                        <div class="col-lg-6">
                                            <label>{{ qi.textoDB('text_form_colca_box') }}</label>
                                            {{ form_widget(form.colorcamiseta) }}
                                        </div>
                                        <div class="col-lg-6">
                                            <label>{{ qi.textoDB('text_form_producto_box') }}</label>
                                            {{ form_widget(form.productotbt) }}
                                        </div>
                                        <div class="col-lg-6">
                                            <label>{{ qi.textoDB('text_tallap_form_box') }}</label>
                                            {{ form_widget(form.tallapantalon) }}
                                        </div>
                                        <div class="col-lg-6">
                                            <label>{{ qi.textoDB('text_colorp_form_box') }}</label>
                                            {{ form_widget(form.colorpantalon) }}
                                        </div>
                                        <div class="col-lg-6">
                                            <label>{{ qi.textoDB('text_tallaz_form_box') }}</label>
                                            {{ form_widget(form.tallazapatos) }}
                                        </div>
                                        <div class="col-lg-12">
                                            <h4>{{ qi.textoDB('address_2')|raw }}  {% if direcciones|length>0 %}<br/> {{ qi.textoDB('address_1') }}{% endif %}</h4>
                                        </div>

                                        {% if direcciones|length>0 %}
                                            <div class=" txt col-lg-12">
                                                 <select id="direccionesuser" name="diruser" required="">
                                                    <option value=""></option>
                                                    {% for d in direcciones %}
                                                        <option {% if diruser|length>0 %}{% if diruser.id ==d.id%}selected {% endif %}{% endif %}value="{{ d.id }}">{{ d.departamento }}-{{ d.ciudad }}-{{ d.direccion }}</option>
                                                    {% endfor %}
                                                </select>

                                            </div>
                                        {% endif %}
                                       <div class=" txt col-lg-12">
                                        <div class="desp">
                                            {% if direcciones|length>0 %}
                                            <a class="button" id="nuevadir">{{ qi.textoDB('boton_nueva') }}</a>
                                            {% endif %}
                                            <div class="item" id="seccformenvio"  {% if direcciones|length==0 %}style="display:block"{% endif %}>
                                                <div class="col-lg-6">
                                                    <label>{{ qi.textoDB('dept_cart') }}</label>
                                                    <select class="envio" id="seldpto" name="departamento" {% if direcciones|length==0 %}required=""{% endif %}>
                                                        <option value=""></option>
                                                        {% for d in departamentos %}
                                                            <option value="{{ d.id }}">{{ d.nombre }}</option>
                                                        {% endfor %}
                                                    </select>
                                                </div>
                                                <div class="col-lg-6">
                                                    <label>{{ qi.textoDB('city_cart') }}</label>
                                                    <select class="envio" id="selciudad" name="ciudad" {% if direcciones|length==0 %}required=""{% endif %}>
                                                    </select>
                                                </div>
                                                <div class="col-lg-6">
                                                    <label>{{ qi.textoDB('dir_cart') }}</label>
                                                    <textarea class="envio" name="direccion" id="direccion"   {% if direcciones|length==0 %}required=""{% endif %}></textarea>
                                                </div>

                                                <div class="col-lg-6">
                                                    <label>{{ qi.textoDB('additional_cart') }}</label>
                                                    <textarea   id="adicional" name="adicionales"></textarea>

                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-xs-12">
                                            <div class="col-lg-6"></div>
                                            <div class="col-lg-6">
                                                <button  type="submit"  class="button float_r">{{ qi.textoDB('box_send') }}</button>
                                            </div>
                                        </div>
                                    </div>


                                    {{ form_end(form) }}
                                </div>
                           </div>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
                    <div class="col-lg-1 col-md-1 col-sm-12 col-xs-12"></div>
                </div>
            </div>
        </div>



    {% endblock %}




{% block javascripts %}
    <script>
        cambiarciudades();

        $('#seldpto').change(function () {
            cambiarciudades();

        });


        $('#direccionesuser').change(function () {
           if($(this).val().length>0){
               $(".envio").prop("required",false);
               $('#seccformenvio').hide();
           }else{
               $(".envio").prop("required",true);
               $('#seccformenvio').show();
           }
        })

        $('#nuevadir').click(function () {

            if(!$(".item").is(":visible")){
                $(".envio").prop("required",true);
                {% if direcciones|length>0 %}
                $("#direccionesuser").prop("required",false)
                $("#direccionesuser").val('');
                {% endif %}
            }else{
                {% if direcciones|length>0 %}
                $(".envio").prop("required",false);
                $("#direccionesuser").prop("required",true)
                {% endif %}
            }
        })

        function cambiarciudades(){
            $.LoadingOverlay("show",{ zIndex: 9999, image: '/js/jquery-loading-overlay/src/loading.gif'});
            $.ajax({
                url: $raiz+"/ciudades-dept/"+$('#seldpto').val(),
            })
                .done(function(html) {
                    $('#selciudad').html(html);
                    costoEnvio();
                })
                .fail(function() {
                })
                .always(function() {
                    $.LoadingOverlay("hide");
                });
        }

        </script>
{% endblock %}

src/CarroiridianBundle/Resources/views/Default/boxes.html.twig
{% extends 'lay_iridian.html.twig' %}

{% block content %}
    {% set categoria = app.request.get('categoria') %}
    {% set genero = app.request.get('genero') %}
    {% set lc = app.request.locale() %}

        <div class="products">

              <div class="list">
               <div class="grid">
                    {% for item in productos %}
                        <div class="item gi grid-item c_ e_ ca_">
                            <div class="img" style="background-image: url({{ path_productos~"/"~item.imagen }})"></div>
                            <div class="img img2" style="background-image: url({{ path_productos~"/"~item.imagenaux }})"></div>
                            <a href="{{ path('boxplan',{id:item.id, nombre: qi.slugify(item.nombre)}) }}"></a>
                            <div class="txt">
                                <div class="cont_center_v">
                                    <h4>{{ item.nombre }}</h4>
                                </div>
                            </div>
                            <div class="oos"><h3>{{ qi.textoDB('store_out_stock') }}</h3></div>
                        </div>
                    {% endfor %}


                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/CarroiridianBundle/Resources/views/Default/cancelacion.html.twig
{% extends 'lay_iridian.html.twig' %}
   {% set lc = app.request.locale %}
{% block content %}

<div class="container gift">
    <div class="row">
        <div class="col-lg-4">
            <div class="txt">
                <h2>{{ producto.nombre }}</h2>
                {{ qi.textoBigBD('texto_cancelación')| raw }}
            </div>
        </div>
        <div class="col-lg-8">
            <div class="img">
                <img alt="" src="{{  path_productos~"/"~producto.imagen }}"/>
            </div>
            <p>{{ qi.textoBigDB("cancelacion-producto") }}</p>
            <a class="button" href="{{ path('make-cancelar',{'id':producto.id}) }}">Cancelar</a>
        </div>
    </div>
</div>

{% endblock %}

src/CarroiridianBundle/Resources/views/Default/ciudades.html.twig
{% for item in ciudades %}
    <option value="{{ item.id }}" data-costo="${{ item.costo | number_format }}" data-costo-noformato="{{ item.costo }}">{{ item.nombre }}</option>
{% endfor %}

src/CarroiridianBundle/Resources/views/Default/datos.html.twig
{% extends 'lay_iridian.html.twig' %}

{% block content %}


    <div class="container log">
        <div class="row">
                <div class="col-lg-6 col-sm-12 col-md-6">
                    {{ form_start(form, {'method': 'post', 'action': '#', 'attr': {'class': 'fos_user_registration_register', "id": "register_form"}}) }}
                        {{ form_errors(form) }}
                        <h4>{{ qi.textoDB('login_have_account') }}</h4>
                        <div class="contenedor">
                            {{ form_errors(form.nombre) }}
                            {{ form_widget(form.nombre, { attr: {'placeholder':qi.textoDB('Nombre')} } ) }}
                        </div>
                        <div class="contenedor">
                            {{ form_errors(form.apellidos) }}
                            {{ form_widget(form.apellidos, { attr: {'placeholder':qi.textoDB('Apellidos')} } ) }}
                        </div>
                        <div class="contenedor">
                            {{ form_errors(form.telefono) }}
                            {{ form_widget(form.telefono, { attr: {'placeholder':qi.textoDB('Teléfono')} } ) }}
                        </div>
                        <div class="contenedor">
                            {{ form_errors(form.email) }}
                            {{ form_widget(form.email, { attr: {'placeholder':qi.textoDB('Email')} } ) }}
                        </div>
                        <div class="contenedor">
                            <label>{{ qi.textoDB('Fecha de nacimeinto') }}</label>
                            {{ form_errors(form.fecha) }}
                            {{ form_widget(form.fecha, { attr: {'placeholder':qi.textoDB('Fecha de nacimeinto'), 'class': 'datepicker'} } ) }}
                        </div>
                        <div class="contenedor">
                            {{ form_errors(form.username) }}
                            {{ form_widget(form.username, { attr: {'placeholder':qi.textoDB('Usuario')} } ) }}
                        </div>
                        <div class="contenedor">
                            {{ form_errors(form.plainPassword.first) }}
                            {{ form_widget(form.plainPassword.first, { attr: {'placeholder':qi.textoDB('Contraseña')} } ) }}
                        </div>
                        <div class="contenedor">
                            {{ form_errors(form.plainPassword.second) }}
                            {{ form_widget(form.plainPassword.second, { attr: {'placeholder':qi.textoDB('Repetir contraseña')} } ) }}
                        </div>
                        <div class="contenedor">
                            <input type="checkbox" required>
                            <p>{{ qi.textoDB('login_terms') }}</p>
                        </div>
                       <div class="contenedor">
                            <input class="button" type="submit" value="{{ qi.textoDB('login_create') }}"/>
                        </div>
                    {{ form_end(form) }}

                </div>
                <div class="col-lg-6 col-sm-12 col-md-6">
                    <form action="{{ path("fos_user_security_check") }}" method="post">
                        <input type="hidden" name="_csrf_token" value="{{ csrf_token }}" />
                        <h4>{{ qi.textoDB('login_login') }}</h4>

                            {% for flashMessage in app.session.flashbag.get('error') %}
                                {# flashMessage #}
                                <br/>
                                <div class="alert alert-danger">
                                    Los datos de usuario o contraseña no son válidos, por favor verifiquelos e intente nuevamente
                                </div>
                            {% endfor %}


                        <div class="contenedor">
                            <input type="text" id="username" name="_username" placeholder="Usuario" required="required" />
                        </div>
                        <div class="contenedor">
                            <input type="password" id="password" name="_password" placeholder="Contraseña" required="required"/>
                        </div>
                        <div class="contenedor">
                            <label class="float_r" for="remember_me">
                                <input type="checkbox" id="remember_me" name="_remember_me" value="on"/> {{ qi.textoDB('login_remember') }}
                            </label>
                        </div>
                        <div class="contenedor">
                            <a class="float_r" href="{{ path('fos_user_resetting_request') }}">{{ qi.textoDB('login_forgot') }}</a>
                        </div>
                          <br/>
                        <input class="button" type="submit" value="{{ qi.textoDB('login_button') }}"/>
                    </form>
                </div>
        </div>
    </div>


    {% include "@Carroiridian/Default/message.html.twig"%}



{% endblock %}

src/CarroiridianBundle/Resources/views/Default/mensaje.html.twig
{% extends 'lay_iridian.html.twig' %}

{% block content %}

<div class="wrapper">
    <div class="carrito">
        {% include 'CarroiridianBundle:Default:pasos.html.twig' %}
        <h4>Muchas gracias por tu compra. Estos son los datos de tu pedido.</h4>

        <div class="row resumen">
            <div class="col-sm-12 col-md-4">
            </div>
            <div class="col-sm-12 col-md-4">
                <div class="col-md-12">
                    <div class="contenedor">
                        <h4>NOMBRE</h4>
                        <p>Fulanito</p>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="contenedor">
                        <h4>DIRECCIÓN</h4>
                        <p>Kra 12 # 45-67</p>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="contenedor">
                        <h4>TELÉFONO</h4>
                        <p>1234567</p>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="contenedor">
                        <h4>TOTAL</h4>
                        <p>1.000.000</p>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="contenedor">
                        <h4>MEDIO DE PAGO</h4>
                        <p>Tarjeta</p>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="contenedor">
                        <a href="{{ path('homepage') }}" class="button">Volver al home</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-4">
            </div>
        </div>

    </div>
</div>

{% endblock %}

src/CarroiridianBundle/Resources/views/Default/misplanes.html.twig
{% extends 'lay_iridian.html.twig' %}

{% block content %}
<div class="container forgot_pass">
    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">
            <div class="fos_user_user_show">
                <p> {{ app.user.username }}</p>
                <p>{{ app.user.email }}</p>
            </div>
        </div>
        <div class="col-lg-4"></div>
    </div>

    <div class="row">
        <h2>{{ qi.textoDB("m_planes") }}</h2>
        <hr/>


             {% if productos|length>0 %}
            <table class="table">
                <thead>
                <th>{{ qi.textoDB('c_produc') }}</th>
                <th></th>
                <th>{{ qi.textoDB('c_price') }}</th>
                <th>{{ qi.textoDB('estado_box') }}</th>
                <th>{{ qi.textoDB('finaliza-suscripcion') }}</th>
                <th></th>

                </thead>
                {% for producto in productos %}
                    <tr>
                        <td>
                            <p><strong>{{ producto.fecha|date('d/m/Y') }}</strong></p>
                            <p>{{ producto.nombre }}</p>
                            <img alt="Bakc to Basic" src="{{ (producto.imagen) | imagine_filter('prod_list_cart') }}"/>

                        </td>
                        <td>
                            <p style="width: 50%; display: inline-block; vertical-align: middle;">
                                <span style="width: 100%; display: inline-block;">{{ producto["direccion"] |raw}}</span>

                            </p>
                        </td>
                        <td>${{ producto.precio | number_format(0) }}</td>
                        <td>{{ producto.estado }}</td>
                        <td>{{ producto.hasta|date('d/m/Y') }}</td>
                        <td><a href="{{ path('cancelar-suscripcion',{'id':producto.idplan}) }}">Cancelar</a></td>
                    </tr>
                  {% endfor %}
             </table>
        {% endif %}

    </div>
</div>
{% endblock %}